/**
 * Interest statuses
 */
export const INTEREST_STATUS = {
  PENDING: 'PENDING',
  EXPIRING: 'EXPIRING',
  EXPIRED: 'EXPIRED',
  THRESHOLD_MET: 'THRESHOLD_MET',
  COLLECTING: 'COLLECTING',
  COMPLETE: 'COMPLETE',
  DIRECT_ORDER_READY: 'DIRECT_ORDER_READY',
  DIRECT_ORDER_PLACED: 'DIRECT_ORDER_PLACED',
  WITHDRAWN: 'WITHDRAWN',
  REFUNDED: 'REFUNDED'
};

/**
 * Order group statuses
 */
export const ORDER_GROUP_STATUS = {
  COLLECTING: 'COLLECTING',
  COMPLETE: 'COMPLETE',
  PLACED: 'PLACED',
  SHIPPED: 'SHIPPED',
  ARRIVED: 'ARRIVED',
  DISTRIBUTING: 'DISTRIBUTING',
  COMPLETED: 'COMPLETED'
};

/**
 * Seller order statuses
 */
export const SELLER_ORDER_STATUS = {
  PLACED: 'PLACED',
  CONFIRMED: 'CONFIRMED',
  SHIPPED: 'SHIPPED',
  IN_TRANSIT: 'IN_TRANSIT',
  ARRIVED: 'ARRIVED',
  DISTRIBUTING: 'DISTRIBUTING',
  COMPLETED: 'COMPLETED'
};

/**
 * Order statuses (fulfillment lifecycle)
 */
export const ORDER_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  PROCESSING: 'PROCESSING',
  SHIPPED: 'SHIPPED',
  IN_TRANSIT: 'IN_TRANSIT',
  ARRIVED: 'ARRIVED',
  READY_FOR_PICKUP: 'READY_FOR_PICKUP',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  PICKED_UP: 'PICKED_UP',
  CANCELLED: 'CANCELLED'
};

/**
 * Tracking statuses (enhanced)
 */
export const TRACKING_STATUS = {
  // Existing statuses
  ORDER_PLACED: 'ORDER_PLACED',
  ORDER_SHIPPED: 'ORDER_SHIPPED',
  ARRIVED_AT_WAREHOUSE: 'ARRIVED_AT_WAREHOUSE',
  READY_FOR_PICKUP: 'READY_FOR_PICKUP',
  PICKED_UP: 'PICKED_UP',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
  // New enhanced statuses
  ORDER_CONFIRMED: 'ORDER_CONFIRMED',
  PAYMENT_RECEIVED_BY_SELLER: 'PAYMENT_RECEIVED_BY_SELLER',
  PROCESSING: 'PROCESSING',
  PACKED: 'PACKED',
  IN_TRANSIT: 'IN_TRANSIT',
  AT_DISTRIBUTION_CENTER: 'AT_DISTRIBUTION_CENTER',
  DELIVERY_ATTEMPTED: 'DELIVERY_ATTEMPTED',
  DELIVERY_RESCHEDULED: 'DELIVERY_RESCHEDULED',
  PICKUP_REMINDER_SENT: 'PICKUP_REMINDER_SENT'
};

/**
 * Payment types
 */
export const PAYMENT_TYPE = {
  DEPOSIT: 'DEPOSIT',
  REMAINING: 'REMAINING',
  LOGISTICS: 'LOGISTICS',
  REFUND: 'REFUND'
};

/**
 * Payment statuses
 */
export const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED'
};

/**
 * Logistics preferences
 */
export const LOGISTICS_PREFERENCE = {
  DELIVERY: 'DELIVERY',
  PICKUP: 'PICKUP'
};

/**
 * User roles
 */
export const USER_ROLE = {
  USER: 'USER',
  ADMIN: 'ADMIN',
  SELLER: 'SELLER'
};

/**
 * Status colors for badges
 */
export const STATUS_COLORS = {
  // Interest statuses
  PENDING: '#ffc107',
  EXPIRING: '#fd7e14',
  THRESHOLD_MET: '#17a2b8',
  COLLECTING: '#007bff',
  COMPLETE: '#28a745',
  DIRECT_ORDER_READY: '#20c997',
  DIRECT_ORDER_PLACED: '#28a745',
  WITHDRAWN: '#6c757d',
  REFUNDED: '#dc3545',
  
  // Order statuses (fulfillment)
  PENDING: '#ffc107',
  CONFIRMED: '#17a2b8',
  PROCESSING: '#007bff',
  SHIPPED: '#17a2b8',
  IN_TRANSIT: '#6f42c1',
  ARRIVED: '#28a745',
  READY_FOR_PICKUP: '#20c997',
  OUT_FOR_DELIVERY: '#fd7e14',
  DELIVERED: '#28a745',
  PICKED_UP: '#28a745',
  CANCELLED: '#dc3545',
  
  // Order group/Seller order statuses
  PLACED: '#007bff',
  DISTRIBUTING: '#ffc107',
  COMPLETED: '#28a745',
  
  // Payment statuses
  COMPLETED: '#28a745',
  PENDING: '#ffc107',
  FAILED: '#dc3545',
  REFUNDED: '#6c757d',
  
  // General
  ACTIVE: '#28a745',
  INACTIVE: '#6c757d'
};

/**
 * Status labels
 */
export const STATUS_LABELS = {
  ...INTEREST_STATUS,
  ...ORDER_GROUP_STATUS,
  ...SELLER_ORDER_STATUS,
  ...TRACKING_STATUS,
  ...PAYMENT_STATUS
};
