-- Seed: Indian States
-- This script seeds all Indian states with their codes

INSERT INTO states (code, name, active) VALUES
('AP', 'Andhra Pradesh', TRUE),
('AR', 'Arunachal Pradesh', TRUE),
('AS', 'Assam', TRUE),
('BR', 'Bihar', TRUE),
('CT', 'Chhattisgarh', TRUE),
('GA', 'Goa', TRUE),
('GJ', 'Gujarat', TRUE),
('HR', 'Haryana', TRUE),
('HP', 'Himachal Pradesh', TRUE),
('JK', 'Jammu and Kashmir', TRUE),
('JH', 'Jharkhand', TRUE),
('KA', 'Karnataka', TRUE),
('KL', 'Kerala', TRUE),
('MP', 'Madhya Pradesh', TRUE),
('MH', 'Maharashtra', TRUE),
('MN', 'Manipur', TRUE),
('ML', 'Meghalaya', TRUE),
('MZ', 'Mizoram', TRUE),
('NL', 'Nagaland', TRUE),
('OR', 'Odisha', TRUE),
('PB', 'Punjab', TRUE),
('RJ', 'Rajasthan', TRUE),
('SK', 'Sikkim', TRUE),
('TN', 'Tamil Nadu', TRUE),
('TG', 'Telangana', TRUE),
('TR', 'Tripura', TRUE),
('UP', 'Uttar Pradesh', TRUE),
('UK', 'Uttarakhand', TRUE),
('WB', 'West Bengal', TRUE),
('AN', 'Andaman and Nicobar Islands', TRUE),
('CH', 'Chandigarh', TRUE),
('DH', 'Dadra and Nagar Haveli and Daman and Diu', TRUE),
('DL', 'Delhi', TRUE),
('LA', 'Ladakh', TRUE),
('LD', 'Lakshadweep', TRUE),
('PY', 'Puducherry', TRUE)
ON CONFLICT DO NOTHING;
